spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_discover
    username: flight_discover
    password: flight_discover
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui